name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Start Selenoid
        uses: Xotabu4/selenoid-github-action@v2
        with:
          browser: chrome
          version: "latest"

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run tests with Selenide
        run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Prepare gh-pages directory
        if: always()
        run: |
          rm -rf gh-pages/*
          cp -r allure-history/* gh-pages/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          publish_branch: gh-pages