name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Start Selenoid
        uses: Xotabu4/selenoid-github-action@v2
        with:
          browser: chrome
          version: "116.0"

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run tests with Selenide
        run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub